name: Deploy to Modal Production

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy:
    if: >
      (github.event_name == 'push' && !contains(github.event.head_commit.message, 'Merge pull request')) ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    env:
      DB: PROD
      
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4

      - name: Checkout workflows repo
        uses: actions/checkout@v4
        with:
          repository: edenartlab/workflows
          path: workflows

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install the latest version of rye
        uses: eifinger/setup-rye@v4

      - name: Install dependencies
        run: rye sync

      - name: Configure Modal token
        run: |
          echo "${{ secrets.MODAL_TOKEN_ID }}" > ~/.modal/token-id
          echo "${{ secrets.MODAL_TOKEN_SECRET }}" > ~/.modal/token-secret

      - name: Deploy to Modal
        run: rye run modal deploy ./eve/api.py
